### ISSUE TITLE
still working?

### ISSUE THREAD

**Issue by therourke** [evlasblom/spotify-lastfm-synchroniser#1]
I just tried this app, and love the idea. It finds my data from spotify and last fm, but then.... nothing. There's no option to sync etc.

Am I missing something, or has this feature been switched off? Thanks

**Comment by evlasblom** [comment]
Could you tell me the exact steps you took and maybe copy a console log? After searching on Spotify for your Last.fm data, the clear and import functions should become available. I just updated my artists again and it all worked without any issues.
